### ISSUE TITLE
Trying to use it on RP2040, but getting an error. I would guess RP2040 should have sufficient specs for encoding

### ISSUE THREAD

**Issue by jensolsson** [pschatzmann/arduino-fdk-aac#10]
This is the error I get

/var/folders/5_/9gsrt3xn33943bbcn4433d5m0000gn/T//ccesJFKN.s: Assembler messages:
/var/folders/5_/9gsrt3xn33943bbcn4433d5m0000gn/T//ccesJFKN.s: Error: unaligned opcodes detected in executable segment

any ideas?

**Comment by pschatzmann** [comment]
I can't reproduce your issue: however I was getting some other compile errors for the Pico that I have corrected in the meantime. My [example sketch](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-webserver/streams-generator-webserver_aac/streams-generator-webserver_aac.ino)  is compiling now w/o issues, but I could not test is...
