### ISSUE TITLE
AudioInfo.bits_per_sample has no effect?

### ISSUE THREAD

**Issue by reiyawea** [pschatzmann/arduino-fdk-aac#11]
I'm using an I2S microphone named INMP441, which is 32 bit per sample (where 24 bit is effective, left-justified).
I tried to set `AudioInfo.bits_per_sample` to 32, resulting in generating a bunch of noise. I also tried to set `AudioInfo.bits_per_sample` to 16 and send 16-bit stereo PCM data through serial port, testing the encoder functioning, which gave an expected aac file.
I searched in this repository and found no where referencing `AACEncoderFDK.bits_per_sample` variable. Maybe the encoder always uses 16 bit per sample regardless of `AudioInfo` settings.
I'm new to arduino world and may asking some foolish questions. Sorry for that.
Thanks a lot.

**Comment by pschatzmann** [comment]
[Google is your friend](https://wiki.hydrogenaud.io/index.php?title=Fraunhofer_FDK_AAC).
and don't ignore the informatioin about the  INMP441 in the Wiki

**Comment by pschatzmann** [comment]
Did you read the link that I have sent your: it states clearly that FDK only supports 16 bits PCM data!

**Comment by reiyawea** [comment]
I sincerely apologise for my carelessness. Please detele this issue.
