### ISSUE TITLE
Decrease memory consumption 

### ISSUE THREAD

**Issue by vernonet** [pschatzmann/arduino-fdk-aac#4]
I found how to reduce memory consumption, initially the fdk encoder consumed about 290KB of RAM, I managed to reduce the consumption to 100KB.

`AACENC_ERROR rc = aacEncOpen(&handle, 0, channels);`
replaced by:
`AACENC_ERROR rc = aacEncOpen(&handle, 1, channels);`

**Comment by franki29** [comment]
HI vernonet, sorry to bother, but can you tell me what you have change to decrease memory consumption?

Thanks and best regards

Frank

**Comment by vernonet** [comment]
In the file "AACENCODERFDK.H" I replaced :
`AACENC_ERROR rc = aacEncOpen(&handle, 0, channels);`
replaced with:
`AACENC_ERROR rc = aacEncOpen(&handle, 1, channels);`
This change is already taken into account in the library.  You can still replace (In "AACENCODERFDK.H"):
`int out_size = 20480; `
replaced with:
`int out_size = 2048; `

**Comment by franki29** [comment]
Thank you very much for your information

**Comment by pschatzmann** [comment]
I just published a new release which contains the proposed optimizations and div error corrections
