### ISSUE TITLE
New Version causes compile error

### ISSUE THREAD

**Issue by franki29** [pschatzmann/arduino-fdk-aac#6]
Hi, after the new changes I get following compile error:
Arduino/libraries/arduino-audio-tools-main/src/AudioCodecs/CodecAACFDK.h:201:14: error: 'class aac_fdk::AACEncoderFDK' has no member named 'setSpecialBandReplication'; did you mean 'setSpectralBandReplication'?
         enc->setSpecialBandReplication(eld_sbr);
              ^~~~~~~~~~~~~~~~~~~~~~~~~
              setSpectralBandReplication

**Comment by pschatzmann** [comment]
I think you are not using the latest version of the library. The AAC encoder has been updated and the corresponding audio-tools-library as well...

**Comment by franki29** [comment]
HI, I did update now also the audio-tools and get a new error:
In file included from /home/frank/Arduino/libraries/arduino-fdk-aac-main/src/libSYS/genericStds.cpp:130:
/home/frank/Arduino/libraries/arduino-fdk-aac-main/src/fdk_log.h: In function 'void printLogFDK(const char*)':
/home/frank/Arduino/libraries/arduino-fdk-aac-main/src/fdk_log.h:39:5: error: 'Serial' was not declared in this scope
     Serial.print(msg);
     ^~~~~~

**Comment by pschatzmann** [comment]
You can deactivate the logging in fdk_log.h by setting
#define FDK_LOGGING_ACTIVE false
I plan to commit a correction tomorrow

**Comment by franki29** [comment]
Hi, Problem gone, it is working now
