### ISSUE TITLE
getting error on Decode example

### ISSUE THREAD

**Issue by arpit-softcircuits** [pschatzmann/arduino-fdk-aac#8]
[E] C:\Users\arpit_ssd\Documents\Arduino\libraries\arduino-fdk-aac-0.3\src\libSYS\genericStds.cpp : 212 - Memory allocations error!!! -> largest free block [8BIT MEMORY: 113792 | 32BIT MEMORY: 113792]

[E] AACDecoderFDK.h : 120 - aacDecoder_Open -> Error

when call aac.begin(); this error comes.
i am using ESP32 wroom 4mb. is this low memory problem or i am doing something wrong.

**Comment by pschatzmann** [comment]
As indicated in the Readme: Decoder needs PSRAM and a 50kbytes stack size!
