### ISSUE TITLE
Hi, can you adapt to Darwin _ x86 _ 64?

### ISSUE THREAD

**Issue by hzhh110** [pschatzmann/arduino-fdk-aac#9]
![image](https://github.com/pschatzmann/arduino-fdk-aac/assets/19906209/4a9eac29-bf03-4937-bcf5-e972c4c3d08c)

**Comment by hzhh110** [comment]
[env:esp32s3camlcd]
platform = espressif32 @^5.2
board = esp32s3camlcd
framework = arduino
board_build.flash_mode = qio
lib_ldf_mode = deep+
board_build.partitions = default_8MB.csv
lib_deps = 
	pschatzmann/arduino-fdk-aac

**Comment by pschatzmann** [comment]
I don't understand your request: The error message is quite speaking: your lib_deps entry is wrong.
It should be https://github.com/pschatzmann/arduino-fdk-aac.git
